### PR TITLE
Adds enter and escape key listeners while in comment variation mode Issue #35

### PR DESCRIPTION
**Pull request by levelonedev**
Cleaned up and moved some of the functions and added a listener.
Removed a variable that wasn't being used ($scope.player.gkRecordingVariation).

I also really mucked up my commit log sorry about that.

### CODE REVIEW

**Comment by neagle** [comment]
For future reference, you can use [`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) to merge together a string of commits into a cleaner single version. That lets you still commit really small chunks as you're developing but bundle it up into a nice package when you're ready to hand it to somebody else.

That said, it's not a big deal. I look forward to looking at this tonight!

**Comment by neagle** [comment]
The enter / escape functionality works great. I did find one unexpected bug, something I hadn't thought about. If you enter / escape out of variation mode, the half-transparent stone marker gets stuck on the board.

We'll need to manually clear that.

gokibitz-bug

**Comment by neagle** [comment]
That problem actually turned out to be pretty easy to fix: 558068f3c13d7798701da6f2d16fd4e4ea06e059

Minor note for the future: make sure you're using tabs instead of spaces! ;) I should actually make sure my gulp process is actually checking / fixing that...

My warmest thanks for doing this! Your taking the time to do this is both helpful and encouraging.

**Comment by levelonedev** [comment]
Gasp. Tabs instead of spaces?! Gross. I'll oblige.

**Comment by neagle** [comment]
You should grab the editorconfig plugin for your text editor of choice: then it'll automatically use the project's settings. :) https://github.com/neagle/gokibitz/blob/master/.editorconfig

(Also: spaces are the worst! ;)

--
Nate Eagle

**Pull request merged**
