### PR TITLE
Adding user notificatons in comments with @

### PR DESCRIPTION
**Pull request by levelonedev**
I already did a lot of talking you through what I've changed so if you have any questions just ask! The only thing I left out was highlighting users in the parseLabel.js section of markdown.

### CODE REVIEW

**Comment by levelonedev** [comment]
This addresses issue #59

**Comment by levelonedev** [comment]
All that's left is to add clicky links to users in comments through parseLablel.js If you have time before I get to it. Go for it!

**Comment by neagle** [comment]
Sweet! I'm excited to check it out. I'm happy to do the clicky links work if I get to it before you, but I'll be a little busy for the next few days with two of my friends' wedding in NC.

**Comment by levelonedev** [comment]
👍

**Comment by neagle** [comment]
As you know, I merged this in today. Thanks a ton for your work on this!

**Pull request merged**
